version: "3"
services:
  app:
    image: guizo/docker-laravel
    ports:
      - 8083:80
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=America/Sao_Paulo
  db:
    image: mysql:5.7
    ports:
      - 33063:3306
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openpad-slim
